### ISSUE TITLE
Generowanie C

### ISSUE THREAD

**Issue by mikolaj24** [piotrmurach/lex#2]
Brakuje mi funkcji generowania kodu C

Łatwo testowac regrex i łatwo to ogarnąć, ale potem chciało by się by to działało szybko i do tego potrzebny jest właśnie kod w C

flex i inne jest strasznie nie dostosowany do innych sposobów niż terminal. błedy są zawsze tam wysyłane.

**Comment by piotrmurach** [comment]
Hey,

Thanks for looking into this project!

The reason for creating this project was to learn more about lexing and create a pure Ruby lex implementation that may, for example, help me build command line arguments and options parser or teach other Ruby devs the principles of constructing other language lexers. 

I do not intend to build any C code generation functionality. If you're interetsed in generating fast lexers then [atlr3](https://github.com/ohboyohboyohboy/antlr3) or  [regel](http://www.colm.net/open-source/ragel/) maybe of interest to yourself. 

However, I would definietly be interestd in implementations of language specific lexers and would happily add them to this gem.
